name: qdense_batchnorm
channels:
  - conda-forge
dependencies:
  - python=3.7
  - jupyter
  - nb_conda
  - ipykernel
  - pip
  - pip:
    - matplotlib
    - numpy
    - PyYAML
    - scikit-learn
    - tensorflow
    - tqdm
    - librosa
    - pandas
    - setGPU
    - git+https://github.com/julesmuhizi/qkeras.git@qdense_batchnorm
<<<<<<< HEAD
    - git+https://github.com/hls4ml-finn-mlperftiny/hls4ml.git@qdense_batchnorm#egg=hls4ml[profiling]
=======
    - git+https://github.com/hls4ml-finn-mlperftiny/hls4ml.git@qdense_batchnorm#egg=hls4ml[profiling]
    # - git+https://github.com/kentaroy47/keras-Opcounter
>>>>>>> 0789d734e9265e9eeeb81c71d71bd7284bf30993
