HLSConfig:
  LayerName:
    input_2:
      Precision: ap_fixed<8,8>
      ReuseFactor: 16384
      Trace: true
      accum_t: ap_fixed<32,16>
    q_activation_5:
      Precision:
        result: ap_ufixed<7,1>
      ReuseFactor: 16384
      Trace: true
      accum_t: ap_fixed<32,16>
    q_activation_6:
      Precision:
        result: ap_ufixed<7,1>
      ReuseFactor: 16384
      Trace: true
      accum_t: ap_fixed<32,16>
    q_activation_7:
      Precision:
        result: ap_ufixed<7,1>
      ReuseFactor: 16384
      Trace: true
      accum_t: ap_fixed<32,16>
    q_activation_8:
      Precision:
        result: ap_ufixed<7,1>
      ReuseFactor: 16384
      Trace: true
      accum_t: ap_fixed<32,16>
    q_activation_9:
      Precision:
        result: ap_ufixed<7,1>
      ReuseFactor: 16384
      Trace: true
      accum_t: ap_fixed<32,16>
    q_dense_6:
      Precision:
        bias: ap_fixed<13,1>
        weight: ap_fixed<13,1>
      ReuseFactor: 16384
      Trace: true
      accum_t: ap_fixed<32,16>
    q_dense_batchnorm:
      Precision:
        bias: ap_fixed<13,1>
        weight: ap_fixed<13,1>
      ReuseFactor: 16384
      Trace: true
      accum_t: ap_fixed<32,16>
    q_dense_batchnorm_1:
      Precision:
        bias: ap_fixed<13,1>
        weight: ap_fixed<13,1>
      ReuseFactor: 16384
      Trace: true
      accum_t: ap_fixed<32,16>
    q_dense_batchnorm_2:
      Precision:
        bias: ap_fixed<13,1>
        weight: ap_fixed<13,1>
      ReuseFactor: 16384
      Trace: true
      accum_t: ap_fixed<32,16>
    q_dense_batchnorm_3:
      Precision:
        bias: ap_fixed<13,1>
        weight: ap_fixed<13,1>
      ReuseFactor: 16384
      Trace: true
      accum_t: ap_fixed<32,16>
    q_dense_batchnorm_4:
      Precision:
        bias: ap_fixed<13,1>
        weight: ap_fixed<13,1>
      ReuseFactor: 16384
      Trace: true
      accum_t: ap_fixed<32,16>
  Model:
    Precision: ap_fixed<32,16>
    ReuseFactor: 16384
    Strategy: Resource
